// Generated by wsdl compiler for android/java
// DO NOT CHANGE!
package skybiz.com.posoffline.m_Ipay88.WebServiceServer.Client;
import skybiz.com.posoffline.m_Ipay88.WebServiceServer.ClientRequestModel;
import skybiz.com.posoffline.m_Ipay88.WebServiceServer.ClientResponseModel;
import com.leansoft.nano.ws.NanoSOAPClient;
import com.leansoft.nano.ws.SOAPServiceCallback;


/**
 This class is the SOAP client to the NumberConversionSoapType Web Service.
*/ 
public class GatewayService_SOAPClient extends NanoSOAPClient {


    /**
     Returns the word corresponding to the positive number passed as parameter. Limited to quadrillions.
    */
   /* public void numberToWords(NumberToWords requestObject, SOAPServiceCallback<NumberToWordsResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, NumberToWordsResponse.class);
    }*/

    /**
     Returns the non-zero dollar amount of the passed number.
    */
    public void clientRequestModel(ClientRequestModel requestObject, SOAPServiceCallback<ClientResponseModel> serviceCallback) {
        super.getAsyncHttpClient().addHeader("SOAPAction", "https://www.mobile88.com/IGatewayService/EntryPageFunctionality");
        super.getAsyncHttpClient().addHeader("message", "tns:IGatewayService_EntryPageFunctionality_InputMessage");
        super.invoke(requestObject, serviceCallback, ClientResponseModel.class);
    }


}