// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package skybiz.com.posoffline.m_Ipay88.WebServiceServer;

import com.leansoft.nano.annotation.AnyElement;
import com.leansoft.nano.annotation.Attribute;
import com.leansoft.nano.annotation.Element;
import com.leansoft.nano.annotation.Order;
import com.leansoft.nano.annotation.RootElement;

import java.io.Serializable;

@RootElement(name = "EntryPageFunctionalityResponse", namespace = "https://www.mobile88.com")
public class ClientResponseModel implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ActionType")
	@Order(value=0)
	public String ActionType;

	@Element(name = "Amount")
	@Order(value=1)
	public String Amount;

	@Element(name = "AuthCode")
	@Order(value=2)
	public String AuthCode;

	@Element(name = "BankMID")
	@Order(value=3)
	public String BankMID;

	@Element(name = "BindCardErrDescc")
	@Order(value=4)
	public String BindCardErrDescc;

	@Element(name = "CCName")
	@Order(value=5)
	public String CCName;

	@Element(name = "CCNo")
	@Order(value=6)
	public String CCNo;

	@Element(name = "CardType")
	@Order(value=7)
	public String CardType;

	@Element(name = "Currency")
	@Order(value=8)
	public String Currency;

	@Element(name = "DCCConversionRate")
	@Order(value=9)
	public String DCCConversionRate;

	@Element(name = "DCCStatus")
	@Order(value=10)
	public String DCCStatus;

	@Element(name = "Discount")
	@Order(value=11)
	public String Discount;

	@Element(name = "ErrDesc")
	@Order(value=12)
	public String ErrDesc;

	@Element(name = "Lang")
	@Order(value=13)
	public String Lang;

	@Element(name = "MerchantCode")
	@Order(value=14)
	public String MerchantCode;

	@Element(name = "OriginalAmount")
	@Order(value=15)
	public String OriginalAmount;

	@Element(name = "OriginalCurrency")
	@Order(value=16)
	public String OriginalCurrency;

	@Element(name = "PaymentId")
	@Order(value=17)
	public String PaymentId;

	@Element(name = "PaymentType")
	@Order(value=18)
	public String PaymentType;

	@Element(name = "QRCode")
	@Order(value=19)
	public String QRCode;

	@Element(name = "QRValue")
	@Order(value=19)
	public String QRValue;

	@Element(name = "RefNo")
	@Order(value=20)
	public String RefNo;

	@Element(name = "Remark")
	@Order(value=21)
	public String Remark;

	@Element(name = "Requery")
	@Order(value=22)
	public String Requery;

	@Element(name = "S_bankname")
	@Order(value=23)
	public String S_bankname;

	@Element(name = "S_country")
	@Order(value=24)
	public String S_country;

	@Element(name = "SettlementAmount")
	@Order(value=25)
	public String SettlementAmount;

	@Element(name = "SettlementCurrency")
	@Order(value=26)
	public String SettlementCurrency;

	@Element(name = "Signature")
	@Order(value=27)
	public String Signature;

	@Element(name = "Status")
	@Order(value=27)
	public String Status;

	@Element(name = "TokenId")
	@Order(value=28)
	public String TokenId;

	@Element(name = "TransId")
	@Order(value=29)
	public String TransId;

	@Element(name = "Xfield1")
	@Order(value=30)
	public String Xfield1;

	@Element(name = "Xfield2")
	@Order(value=31)
	public String Xfield2;

}