// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package skybiz.com.posoffline.m_Ipay88.WebServiceServer;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.math.BigDecimal;

@RootElement(name = "EntryPageFunctionality", namespace = "https://www.mobile88.com")
public class ClientRequestModel implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ActionType")
	@Order(value=0)
	public String ActionType;

	@Element(name = "Amount")
	@Order(value=1)
	public String Amount;

	@Element(name = "BackendURL")
	@Order(value=2)
	public String BackendURL;

	@Element(name = "BarcodeNo")
	@Order(value=3)
	public String BarcodeNo;

	@Element(name = "CCCId")
	@Order(value=4)
	public String CCCId;

	@Element(name = "CCCOriTokenId")
	@Order(value=5)
	public String CCCOriTokenId;

	@Element(name = "CCMonth")
	@Order(value=6)
	public String CCMonth;

	@Element(name = "CCName")
	@Order(value=7)
	public String CCName;

	@Element(name = "CCNo")
	@Order(value=8)
	public String CCNo;

	@Element(name = "CCYear")
	@Order(value=9)
	public String CCYear;

	@Element(name = "CVV2")
	@Order(value=10)
	public String CVV2;

	@Element(name = "Currency")
	@Order(value=11)
	public String Currency;

	@Element(name = "MTLogId")
	@Order(value=12)
	public String MTLogId;

	@Element(name = "MTVersion")
	@Order(value=13)
	public String MTVersion;

	@Element(name = "MerchantCode")
	@Order(value=14)
	public String MerchantCode;

	@Element(name = "PaymentId")
	@Order(value=15)
	public String PaymentId;

	@Element(name = "ProdDesc")
	@Order(value=16)
	public String ProdDesc;

	@Element(name = "RefNo")
	@Order(value=17)
	public String RefNo;

	@Element(name = "Remark")
	@Order(value=18)
	public String Remark;

	@Element(name = "Signature")
	@Order(value=19)
	public String Signature;

	@Element(name = "SignatureType")
	@Order(value=20)
	public String SignatureType;

	@Element(name = "TerminalID")
	@Order(value=21)
	public String TerminalID;

	@Element(name = "TokenId")
	@Order(value=21)
	public String TokenId;

	@Element(name = "UserContact")
	@Order(value=22)
	public String UserContact;

	@Element(name = "UserEmail")
	@Order(value=23)
	public String UserEmail;

	@Element(name = "UserName")
	@Order(value=24)
	public String UserName;

	@Element(name = "forexRate")
	@Order(value=25)
	public String forexRate;

	@Element(name = "lang")
	@Order(value=26)
	public String lang;

	@Element(name = "xfield1")
	@Order(value=27)
	public String xfield1;

	@Element(name = "xfield2")
	@Order(value=28)
	public String xfield2;

}