// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package skybiz.com.posoffline.m_Ipay88.WebServiceServer;

import com.leansoft.nano.annotation.Element;
import com.leansoft.nano.annotation.Order;
import com.leansoft.nano.annotation.RootElement;

import java.io.Serializable;

@RootElement(name = "NumberToWordsResponse", namespace = "http://www.dataaccess.com/webservicesserver/")
public class NumberToWordsResponse implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "NumberToWordsResult")
	@Order(value=0)
	public String numberToWordsResult;	
	
    
}