// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package skybiz.com.posoffline.m_Ipay88.WebServiceServer;

import com.leansoft.nano.annotation.Element;
import com.leansoft.nano.annotation.Order;
import com.leansoft.nano.annotation.RootElement;

import java.io.Serializable;
import java.math.BigInteger;

@RootElement(name = "NumberToWords", namespace = "http://www.dataaccess.com/webservicesserver/")
public class NumberToWords implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	@Order(value=0)
	public BigInteger ubiNum;	
	
    
}