package skybiz.com.posoffline.m_Ipay88.Service;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class FKJClientRequestModel extends AttributeContainer implements KvmSerializable
{

    
    public String ActionType;
    
    public String Amount;
    
    public String BackendURL;
    
    public String BarcodeNo;
    
    public String CCCId;
    
    public String CCCOriTokenId;
    
    public String CCMonth;
    
    public String CCName;
    
    public String CCNo;
    
    public String CCYear;
    
    public String CVV2;
    
    public String Currency;
    
    public String MTLogId;
    
    public String MTVersion;
    
    public String MerchantCode;
    
    public Integer PaymentId;
    
    public String ProdDesc;
    
    public String RefNo;
    
    public String Remark;
    
    public String Signature;
    
    public String SignatureType;
    
    public String TerminalID;
    
    public String TokenId;
    
    public String UserContact;
    
    public String UserEmail;
    
    public String UserName;
    
    public String forexRate;
    
    public String lang;
    
    public String xfield1;
    
    public String xfield2;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,FKJExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,FKJExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("ActionType"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ActionType = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ActionType = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Amount"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Amount = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Amount = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("BackendURL"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.BackendURL = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.BackendURL = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("BarcodeNo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.BarcodeNo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.BarcodeNo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CCCId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CCCId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CCCId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CCCOriTokenId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CCCOriTokenId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CCCOriTokenId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CCMonth"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CCMonth = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CCMonth = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CCName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CCName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CCName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CCNo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CCNo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CCNo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CCYear"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CCYear = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CCYear = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CVV2"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CVV2 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CVV2 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Currency"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Currency = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Currency = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("MTLogId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MTLogId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.MTLogId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("MTVersion"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MTVersion = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.MTVersion = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("MerchantCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MerchantCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.MerchantCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("PaymentId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.PaymentId = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.PaymentId = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ProdDesc"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ProdDesc = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ProdDesc = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("RefNo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.RefNo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.RefNo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Remark"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Remark = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Remark = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Signature"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Signature = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Signature = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SignatureType"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SignatureType = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.SignatureType = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TerminalID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TerminalID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TerminalID = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TokenId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TokenId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TokenId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("UserContact"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.UserContact = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.UserContact = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("UserEmail"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.UserEmail = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.UserEmail = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("UserName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.UserName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.UserName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("forexRate"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.forexRate = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.forexRate = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("lang"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.lang = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.lang = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("xfield1"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.xfield1 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.xfield1 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("xfield2"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.xfield2 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.xfield2 = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.ActionType!=null?this.ActionType:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.Amount!=null?this.Amount:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.BackendURL!=null?this.BackendURL:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.BarcodeNo!=null?this.BarcodeNo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.CCCId!=null?this.CCCId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.CCCOriTokenId!=null?this.CCCOriTokenId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.CCMonth!=null?this.CCMonth:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.CCName!=null?this.CCName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.CCNo!=null?this.CCNo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.CCYear!=null?this.CCYear:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.CVV2!=null?this.CVV2:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.Currency!=null?this.Currency:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.MTLogId!=null?this.MTLogId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.MTVersion!=null?this.MTVersion:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.MerchantCode!=null?this.MerchantCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return this.PaymentId!=null?this.PaymentId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==16)
        {
            return this.ProdDesc!=null?this.ProdDesc:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==17)
        {
            return this.RefNo!=null?this.RefNo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==18)
        {
            return this.Remark!=null?this.Remark:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==19)
        {
            return this.Signature!=null?this.Signature:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==20)
        {
            return this.SignatureType!=null?this.SignatureType:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==21)
        {
            return this.TerminalID!=null?this.TerminalID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==22)
        {
            return this.TokenId!=null?this.TokenId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==23)
        {
            return this.UserContact!=null?this.UserContact:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==24)
        {
            return this.UserEmail!=null?this.UserEmail:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==25)
        {
            return this.UserName!=null?this.UserName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==26)
        {
            return this.forexRate!=null?this.forexRate:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==27)
        {
            return this.lang!=null?this.lang:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==28)
        {
            return this.xfield1!=null?this.xfield1:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==29)
        {
            return this.xfield2!=null?this.xfield2:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 30;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ActionType";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Amount";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "BackendURL";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "BarcodeNo";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CCCId";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CCCOriTokenId";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CCMonth";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CCName";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CCNo";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CCYear";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CVV2";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Currency";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MTLogId";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MTVersion";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MerchantCode";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "PaymentId";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ProdDesc";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "RefNo";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Remark";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==19)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Signature";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==20)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SignatureType";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==21)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TerminalID";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==22)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TokenId";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==23)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "UserContact";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==24)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "UserEmail";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==25)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "UserName";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==26)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "forexRate";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==27)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "lang";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==28)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "xfield1";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==29)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "xfield2";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
    }

    @Override
    public void setProperty(int i, java.lang.Object o) {
        switch (i){
            case 0:
                ActionType = o.toString();
                break;
            case 1:
                Amount = o.toString();
                break;
            case 2:
                BackendURL = o.toString();
                break;
            case 3:
                BarcodeNo = o.toString();
                break;
            case 4:
                CCCId = o.toString();
                break;
            case 5:
                CCCOriTokenId = o.toString();
            case 6:
                CCMonth = o.toString();
                break;
            case 7:
                CCName = o.toString();
                break;
            case 8:
                CCNo = o.toString();
                break;
            case 9:
                CCYear = o.toString();
                break;
            case 10:
                CVV2 = o.toString();
                break;
            case 11:
                Currency = o.toString();
                break;
            case 12:
                MTLogId = o.toString();
                break;
            case 13:
                MTVersion = o.toString();
                break;
            case 14:
                MerchantCode = o.toString();
                break;
            case 15:
                PaymentId = Integer.parseInt(o.toString());
                break;
            case 16:
                ProdDesc = o.toString();
                break;
            case 17:
                RefNo = o.toString();
                break;
            case 18:
                Remark = o.toString();
                break;
            case 19:
                Signature = o.toString();
                break;
            case 20:
                SignatureType = o.toString();
                break;
            case 21:
                TerminalID = o.toString();
                break;
            case 22:
                TokenId = o.toString();
                break;
            case 23:
                UserContact = o.toString();
                break;
            case 24:
                UserEmail = o.toString();
                break;
            case 25:
                UserName = o.toString();
                break;
            case 26:
                forexRate = o.toString();
                break;
            case 27:
                lang = o.toString();
                break;
            case 28:
                xfield1 = o.toString();
                break;
            case 29:
                xfield2 = o.toString();
                break;
            default:
                break;
        }
    }


                    /*
      BackendURL; BarcodeNo; CCCId; CCCOriTokenId;CCMonth; CCName;CCNo;CCYear; CVV2; Currency; MTLogId;
     String MTVersion; String MerchantCode; Integer PaymentId; String ProdDesc; RefNo; String Remark; String Signature;
     String SignatureType; String TerminalID; String TokenId;String UserContact; String UserEmail;
     String UserName; String forexRate; String lang;
   String xfield1; String xfield2;
     */
}

