package skybiz.com.posoffline.m_Ipay88.Service;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class FKJClientResponseModel extends AttributeContainer implements KvmSerializable
{

    
    public String ActionType;
    
    public String Amount;
    
    public String AuthCode;
    
    public String BankMID;
    
    public String BindCardErrDescc;
    
    public String CCName;
    
    public String CCNo;
    
    public String CardType;
    
    public String Currency;
    
    public String DCCConversionRate;
    
    public Integer DCCStatus;
    
    public String Discount;
    
    public String ErrDesc;
    
    public String Lang;
    
    public String MerchantCode;
    
    public String OriginalAmount;
    
    public String OriginalCurrency;
    
    public Integer PaymentId;
    
    public String PaymentType;
    
    public String QRCode;
    
    public String QRValue;
    
    public String RefNo;
    
    public String Remark;
    
    public String Requery;
    
    public String S_bankname;
    
    public String S_country;
    
    public String SettlementAmount;
    
    public String SettlementCurrency;
    
    public String Signature;
    
    public Integer Status;
    
    public String TokenId;
    
    public String TransId;
    
    public String Xfield1;
    
    public String Xfield2;
    private transient java.lang.Object __source;    

    public void loadFromSoap(java.lang.Object paramObj,FKJExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,FKJExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("ActionType"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ActionType = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ActionType = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Amount"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Amount = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Amount = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("AuthCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.AuthCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.AuthCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("BankMID"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.BankMID = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.BankMID = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("BindCardErrDescc"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.BindCardErrDescc = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.BindCardErrDescc = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CCName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CCName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CCName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CCNo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CCNo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CCNo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CardType"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CardType = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CardType = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Currency"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Currency = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Currency = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DCCConversionRate"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DCCConversionRate = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.DCCConversionRate = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DCCStatus"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DCCStatus = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.DCCStatus = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Discount"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Discount = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Discount = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ErrDesc"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ErrDesc = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ErrDesc = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Lang"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Lang = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Lang = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("MerchantCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MerchantCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.MerchantCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("OriginalAmount"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.OriginalAmount = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.OriginalAmount = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("OriginalCurrency"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.OriginalCurrency = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.OriginalCurrency = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("PaymentId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.PaymentId = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.PaymentId = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("PaymentType"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.PaymentType = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.PaymentType = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("QRCode"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.QRCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.QRCode = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("QRValue"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.QRValue = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.QRValue = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("RefNo"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.RefNo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.RefNo = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Remark"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Remark = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Remark = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Requery"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Requery = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Requery = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("S_bankname"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.S_bankname = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.S_bankname = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("S_country"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.S_country = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.S_country = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SettlementAmount"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SettlementAmount = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.SettlementAmount = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("SettlementCurrency"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.SettlementCurrency = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.SettlementCurrency = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Signature"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Signature = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Signature = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Status"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Status = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.Status = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TokenId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TokenId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TokenId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TransId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TransId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.TransId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Xfield1"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Xfield1 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Xfield1 = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Xfield2"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Xfield2 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Xfield2 = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.ActionType!=null?this.ActionType:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.Amount!=null?this.Amount:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.AuthCode!=null?this.AuthCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.BankMID!=null?this.BankMID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.BindCardErrDescc!=null?this.BindCardErrDescc:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.CCName!=null?this.CCName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.CCNo!=null?this.CCNo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.CardType!=null?this.CardType:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.Currency!=null?this.Currency:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.DCCConversionRate!=null?this.DCCConversionRate:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.DCCStatus!=null?this.DCCStatus:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.Discount!=null?this.Discount:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.ErrDesc!=null?this.ErrDesc:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.Lang!=null?this.Lang:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.MerchantCode!=null?this.MerchantCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return this.OriginalAmount!=null?this.OriginalAmount:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==16)
        {
            return this.OriginalCurrency!=null?this.OriginalCurrency:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==17)
        {
            return this.PaymentId!=null?this.PaymentId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==18)
        {
            return this.PaymentType!=null?this.PaymentType:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==19)
        {
            return this.QRCode!=null?this.QRCode:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==20)
        {
            return this.QRValue!=null?this.QRValue:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==21)
        {
            return this.RefNo!=null?this.RefNo:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==22)
        {
            return this.Remark!=null?this.Remark:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==23)
        {
            return this.Requery!=null?this.Requery:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==24)
        {
            return this.S_bankname!=null?this.S_bankname:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==25)
        {
            return this.S_country!=null?this.S_country:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==26)
        {
            return this.SettlementAmount!=null?this.SettlementAmount:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==27)
        {
            return this.SettlementCurrency!=null?this.SettlementCurrency:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==28)
        {
            return this.Signature!=null?this.Signature:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==29)
        {
            return this.Status!=null?this.Status:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==30)
        {
            return this.TokenId!=null?this.TokenId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==31)
        {
            return this.TransId!=null?this.TransId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==32)
        {
            return this.Xfield1!=null?this.Xfield1:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==33)
        {
            return this.Xfield2!=null?this.Xfield2:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 34;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ActionType";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Amount";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AuthCode";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "BankMID";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "BindCardErrDescc";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CCName";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CCNo";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CardType";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Currency";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DCCConversionRate";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "DCCStatus";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Discount";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ErrDesc";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Lang";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MerchantCode";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "OriginalAmount";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "OriginalCurrency";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "PaymentId";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "PaymentType";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==19)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "QRCode";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==20)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "QRValue";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==21)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "RefNo";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==22)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Remark";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==23)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Requery";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==24)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "S_bankname";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==25)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "S_country";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==26)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SettlementAmount";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==27)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SettlementCurrency";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==28)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Signature";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==29)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "Status";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==30)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TokenId";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==31)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TransId";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==32)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Xfield1";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
        if(propertyIndex==33)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Xfield2";
            info.namespace= "http://schemas.datacontract.org/2004/07/MHPHGatewayService.Model";
        }
    }
    
    @Override
    public void setProperty(int i, java.lang.Object o) {
        switch (i){
            case 0:
                ActionType = o.toString();
                break;
            case 1:
                Amount = o.toString();
                break;
            case 2:
                AuthCode = o.toString();
                break;
            case 3:
                BankMID = o.toString();
                break;
            case 4:
                BindCardErrDescc = o.toString();
                break;
            case 5:
                CCName = o.toString();
            case 6:
                CardType = o.toString();
                break;
            case 7:
                Currency = o.toString();
                break;
            case 8:
                DCCConversionRate = o.toString();
                break;
            case 9:
                DCCStatus = Integer.parseInt(o.toString());
                break;
            case 10:
                Discount = o.toString();
                break;
            case 11:
                ErrDesc = o.toString();
                break;
            case 12:
                Lang = o.toString();
                break;
            case 13:
                MerchantCode = o.toString();
                break;
            case 14:
                OriginalAmount = o.toString();
                break;
            case 15:
                OriginalCurrency =o.toString();
                break;
            case 16:
                PaymentId = Integer.parseInt(o.toString());
                break;
            case 17:
                PaymentType = o.toString();
                break;
            case 18:
                QRCode = o.toString();
                break;
            case 19:
                QRValue = o.toString();
                break;
            case 20:
                RefNo = o.toString();
                break;
            case 21:
                Remark = o.toString();
                break;
            case 22:
                Requery = o.toString();
                break;
            case 23:
                Requery = o.toString();
                break;
            case 24:
                S_bankname = o.toString();
                break;
            case 25:
                S_country = o.toString();
                break;
            case 26:
                SettlementAmount = o.toString();
                break;
            case 27:
                SettlementCurrency = o.toString();
                break;
            case 28:
                Signature =o.toString();
            case 29:
                Status =Integer.parseInt(o.toString());
                break;
            case 30:
                TokenId = o.toString();
                break;
            case 31:
                TransId = o.toString();
                break;
            case 32:
                Xfield1 = o.toString();
                break;
            case 33:
                Xfield2 = o.toString();
                break;
            default:
                break;
        }
    }

    
}

